Make grep more fault tolerant

diff --git a/.github/actions/test-external-links/action.yml b/.github/actions/test-external-links/action.yml
--- a/.github/actions/test-external-links/action.yml
+++ b/.github/actions/test-external-links/action.yml
@@ -68,7 +68,8 @@ runs:
                     fi
 
                     if [[ "${status}" -eq 404 ]]; then
-                        locations=$(grep -rl "${url}")
+                        # In the event of unicode control characters, grep's behaviour may be unpredictable - but lets not fail the workflow for that
+                        locations=$(grep -rl "${url}" || true)
                         echo "::error::❌ URL '${url}' had status ${status} (found in ${locations})" 1>&2
                         found_error=1
                     else
