add org validation

diff --git a/.github/workflows/deploy-preview.yml b/.github/workflows/deploy-preview.yml
--- a/.github/workflows/deploy-preview.yml
+++ b/.github/workflows/deploy-preview.yml
@@ -1,15 +1,35 @@
 name: Deploy preview
 
 on:
-  pull_request:
+  pull_request_target:
     branches: [main, 'v/*']
   workflow_dispatch:
 
 jobs:
+  check_for_membership:
+    runs-on: ubuntu-latest
+    name: Check PR author membership
+    outputs:
+      check-result: ${{ steps.composite.outputs.check-result }}
+    steps:
+      - name: Action for membership check
+        id: composite
+        uses: hazelcast/hazelcast-tpm/membership@main
+        with:
+          member-name: ${{ github.triggering_actor }}
+          token: ${{ secrets.GH_TOKEN }}
+
   build-and-deploy:
     runs-on: ubuntu-latest
+    needs: check_for_membership
 
     steps:
+      - name: Detect untrusted community PR
+        if: ${{ needs.check_for_membership.outputs.check-result == 'false' && github.event.pull_request.user.login != 'dependabot[bot]' }}
+        run: |
+          echo "::error::Untrusted external PR. Must be reviewed and executed by Hazelcast"
+          exit 1
+
       - uses: actions/checkout@v6
 
       - uses: actions/setup-node@v6
